// This file is generated by a build script; please DO NOT EDIT.

#ifndef MIRAICP_BOTCONFIG_H
#define MIRAICP_BOTCONFIG_H

#include "MiraiCPMacros.h"
#include "commonTypes.h"
#include <unordered_map>

struct QQinfo {
    MiraiCP::QQID MASTERID;
    MiraiCP::QQID BOTID;
    std::unordered_map<std::string, std::string> ai_list;
};

extern const QQinfo QQCONFIG;

#endif //MIRAICP_BOTCONFIG_H
